revision: v1
type: plugin
name: XYZ
versions:
  - version: 1.0.6
    from: poggit_pmmp
  - version: 1.0.5
    from: poggit_pmmp
  - version: 1.0.4
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
