revision: v1
type: plugin
name: OffHand
versions:
  - version: 2.1.4
    from: poggit_pmmp
  - version: 2.1.3
    from: poggit_pmmp
  - version: 2.1.2
    from: poggit_pmmp
  - version: 2.1.1
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.5
    from: poggit_pmmp
  - version: 2.0.4
    from: poggit_pmmp
  - version: 2.0.3
    from: poggit_pmmp
  - version: 2.0.2
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
  - version: 1.1.2
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
