revision: v1
type: plugin
name: MultiVersion
versions:
  - version: 0.475.1
    from: poggit_pmmp
  - version: 0.471.4
    from: poggit_pmmp
  - version: 0.471.3
    from: poggit_pmmp
  - version: 0.471.2
    from: poggit_pmmp
  - version: 0.471.1
    from: poggit_pmmp
  - version: '0.471'
    from: poggit_pmmp
