revision: v1
type: plugin
name: ServerTools
versions:
  - version: 0.3.2
    from: poggit_pmmp
  - version: 0.3.1
    from: poggit_pmmp
  - version: 0.3.0
    from: poggit_pmmp
  - version: 0.1.0
    from: poggit_pmmp
