revision: v1
type: plugin
name: MakeMeAdmin
versions:
  - version: 1.6.0
    from: poggit_pmmp
  - version: 1.5.2
    from: poggit_pmmp
  - version: 1.5.1
    from: poggit_pmmp
  - version: 1.5.0
    from: poggit_pmmp
