revision: v1
type: plugin
name: BedWars
versions:
  - version: 1.1.8
    from: poggit_pmmp
  - version: 1.1.7
    from: poggit_pmmp
  - version: 1.1.6
    from: poggit_pmmp
  - version: 1.1.5
    from: poggit_pmmp
  - version: 1.1.4
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
