revision: v1
type: plugin
name: Track
versions:
  - version: 0.0.8
    from: poggit_pmmp
  - version: 0.0.7
    from: poggit_pmmp
  - version: 0.0.6
    from: poggit_pmmp
  - version: 0.0.5
    from: poggit_pmmp
  - version: 0.0.4
    from: poggit_pmmp
  - version: 0.0.3
    from: poggit_pmmp
  - version: 0.0.2
    from: poggit_pmmp
  - version: 0.0.1
    from: poggit_pmmp
