revision: v1
type: plugin
name: CustomNPC
versions:
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
  - version: 1.1.2
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
