revision: v1
type: plugin
name: AlwaysSpawn
versions:
  - version: 2.2.5
    from: poggit_pmmp
  - version: 2.2.4
    from: poggit_pmmp
  - version: 2.2.3-6
    from: poggit_pmmp
  - version: 2.2.3-5
    from: poggit_pmmp
  - version: 2.2.3-4
    from: poggit_pmmp
  - version: 2.2.3-3
    from: poggit_pmmp
  - version: 2.2.3-2.alpha8
    from: poggit_pmmp
  - version: 2.2.3-dev1
    from: poggit_pmmp
  - version: 2.2.2-dev1
    from: poggit_pmmp
  - version: 2.2.2
    from: poggit_pmmp
  - version: 2.2.0-old
    from: poggit_pmmp
