revision: v1
type: plugin
name: PiggyCrates
versions:
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.9
    from: poggit_pmmp
  - version: 2.0.8
    from: poggit_pmmp
  - version: 2.0.7
    from: poggit_pmmp
  - version: 2.0.6
    from: poggit_pmmp
  - version: 2.0.5
    from: poggit_pmmp
  - version: 2.0.4
    from: poggit_pmmp
  - version: 2.0.3
    from: poggit_pmmp
  - version: 2.0.2
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.5.1
    from: poggit_pmmp
  - version: 1.5.0
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.3.0
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
