revision: v1
type: plugin
name: SimpleLay
versions:
  - version: 2.1.10
    from: poggit_pmmp
  - version: 2.1.9
    from: poggit_pmmp
  - version: 2.1.8
    from: poggit_pmmp
  - version: 2.1.7
    from: poggit_pmmp
  - version: 2.1.6
    from: poggit_pmmp
  - version: 2.1.5
    from: poggit_pmmp
  - version: 2.1.4
    from: poggit_pmmp
  - version: 2.1.3
    from: poggit_pmmp
  - version: 2.1.2
    from: poggit_pmmp
  - version: 2.1.1
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
