revision: v1
type: plugin
name: EconomyLand
versions:
  - version: 2.1.2
    from: poggit_pmmp
  - version: 2.1.1-5
    from: poggit_pmmp
  - version: 2.1.1-4
    from: poggit_pmmp
  - version: 2.1.1-3
    from: poggit_pmmp
  - version: 2.1.1-2
    from: poggit_pmmp
  - version: 2.1.1-1.alpha8
    from: poggit_pmmp
  - version: 2.1.0-dev1
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.9
    from: poggit_pmmp
