revision: v1
type: plugin
name: BlockSniper
versions:
  - version: 3.2.3
    from: poggit_pmmp
  - version: 3.2.2
    from: poggit_pmmp
  - version: 3.2.1
    from: poggit_pmmp
  - version: 3.2.0
    from: poggit_pmmp
  - version: 3.1.1
    from: poggit_pmmp
  - version: 3.1.0
    from: poggit_pmmp
  - version: 3.0.4
    from: poggit_pmmp
  - version: 3.0.3
    from: poggit_pmmp
  - version: 3.0.2
    from: poggit_pmmp
  - version: 3.0.1
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
  - version: 2.3.1
    from: poggit_pmmp
  - version: 2.3.0
    from: poggit_pmmp
  - version: 2.2.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.3.1
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 0.2.0
    from: poggit_pmmp
