revision: v1
type: plugin
name: EventSounds
versions:
  - version: 0.4.2
    from: poggit_pmmp
  - version: 0.4.1
    from: poggit_pmmp
  - version: 0.4.0
    from: poggit_pmmp
  - version: 0.2.0
    from: poggit_pmmp
