revision: v1
type: plugin
name: PM-Beacons
versions:
  - version: 2.0.2
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.0.8
    from: poggit_pmmp
  - version: 1.0.7
    from: poggit_pmmp
  - version: 1.0.6
    from: poggit_pmmp
  - version: 1.0.5-1
    from: poggit_pmmp
  - version: 1.0.5
    from: poggit_pmmp
  - version: 1.0.4-1
    from: poggit_pmmp
  - version: 1.0.4
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
  - version: 0.1.2
    from: poggit_pmmp
  - version: 0.1.1
    from: poggit_pmmp
