revision: v1
type: plugin
name: EconomyAPI
versions:
  - version: 5.7.3-PM4
    from: poggit_pmmp
  - version: 5.7.2
    from: poggit_pmmp
  - version: 5.7.1-6
    from: poggit_pmmp
  - version: 5.7.1-5
    from: poggit_pmmp
  - version: 5.7.1-4
    from: poggit_pmmp
  - version: 5.7.1-3
    from: poggit_pmmp
  - version: 5.7.1-2.alpha8
    from: poggit_pmmp
  - version: 5.7.1-dev1
    from: poggit_pmmp
  - version: 5.7.1
    from: poggit_pmmp
  - version: '5.7'
    from: poggit_pmmp
  - version: '5.0'
    from: poggit_pmmp
