revision: v1
type: plugin
name: KOTH
versions:
  - version: 1.0.0-Beta4
    from: poggit_pmmp
  - version: 1.0.0-Beta3
    from: poggit_pmmp
  - version: 1.0.0-Beta2
    from: poggit_pmmp
  - version: 1.0.0-Beta1
    from: poggit_pmmp
