revision: v1
type: plugin
name: Mineflow
versions:
  - version: 2.6.1
    from: poggit_pmmp
  - version: 2.6.0
    from: poggit_pmmp
  - version: 2.5.2
    from: poggit_pmmp
  - version: 2.5.0
    from: poggit_pmmp
  - version: 2.4.0
    from: poggit_pmmp
  - version: 2.3.1
    from: poggit_pmmp
  - version: 2.3.0
    from: poggit_pmmp
  - version: 2.2.1
    from: poggit_pmmp
  - version: 2.2.0
    from: poggit_pmmp
  - version: 2.1.1
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.3
    from: poggit_pmmp
  - version: 2.0.2
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.3.1
    from: poggit_pmmp
  - version: 1.3.0
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
  - version: 0.7.0
    from: poggit_pmmp
  - version: 0.6.2
    from: poggit_pmmp
  - version: 0.6.1
    from: poggit_pmmp
  - version: 0.6.0
    from: poggit_pmmp
  - version: 0.4.1
    from: poggit_pmmp
  - version: 0.3.1
    from: poggit_pmmp
  - version: 0.3.0
    from: poggit_pmmp
  - version: 0.1.0
    from: poggit_pmmp
