revision: v1
type: plugin
name: HotBlock
versions:
  - version: 1.1.6
    from: poggit_pmmp
  - version: 1.1.5
    from: poggit_pmmp
  - version: 1.1.4
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
  - version: 1.1.2
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.0.9
    from: poggit_pmmp
  - version: 1.0.7
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
