revision: v1
type: plugin
name: LockedItem
versions:
  - version: 4.0.0
    from: poggit_pmmp
  - version: 3.0.1
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
