revision: v1
type: plugin
name: LobbyPlayerLimit
versions:
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: '1.1'
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
