revision: v1
type: plugin
name: PTimeUI
versions:
  - version: 1.0.3-5
    from: poggit_pmmp
  - version: 1.0.3-3
    from: poggit_pmmp
  - version: 1.0.3-2
    from: poggit_pmmp
  - version: 1.0.3-1
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
