revision: v1
type: plugin
name: ItemCase
versions:
  - version: 1.2.5
    from: poggit_pmmp
  - version: 1.2.3
    from: poggit_pmmp
  - version: 1.2.2
    from: poggit_pmmp
  - version: 1.2.1-3
    from: poggit_pmmp
  - version: 1.2.1-2
    from: poggit_pmmp
  - version: 1.2.1-1
    from: poggit_pmmp
  - version: 1.2.1
    from: poggit_pmmp
  - version: 1.2.0-alpha8
    from: poggit_pmmp
  - version: 1.1.0-dev1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
