revision: v1
type: plugin
name: SimplePets
versions:
  - version: 1.0.4-beta
    from: poggit_pmmp
  - version: 1.0.3-beta
    from: poggit_pmmp
  - version: 1.0.2-beta
    from: poggit_pmmp
  - version: 1.0.1-beta
    from: poggit_pmmp
  - version: 1.0.0-beta
    from: poggit_pmmp
