revision: v1
type: plugin
name: SimpleAuthHelper
versions:
  - version: 2.0.8
    from: poggit_pmmp
  - version: 2.0.7
    from: poggit_pmmp
  - version: 2.0.6-7
    from: poggit_pmmp
  - version: 2.0.6-6
    from: poggit_pmmp
  - version: 2.0.6-5
    from: poggit_pmmp
  - version: 2.0.6-3
    from: poggit_pmmp
  - version: 2.0.6-1.alpha8
    from: poggit_pmmp
  - version: 2.0.6
    from: poggit_pmmp
  - version: 2.0.5-dev1
    from: poggit_pmmp
  - version: 2.0.5
    from: poggit_pmmp
  - version: 2.0.4
    from: poggit_pmmp
