revision: v1
type: plugin
name: cucumber
versions:
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.6.2
    from: poggit_pmmp
  - version: 1.5.0
    from: poggit_pmmp
  - version: 1.3.1
    from: poggit_pmmp
  - version: 1.2.1
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
