revision: v1
type: plugin
name: EC-TableUI
versions:
  - version: 1.1.2-pre
    from: poggit_pmmp
  - version: 1.1.1-pre
    from: poggit_pmmp
  - version: 1.1.0-pre
    from: poggit_pmmp
  - version: 1.0.0-pre
    from: poggit_pmmp
