revision: v1
type: plugin
name: BurgerSpawners
versions:
  - version: 0.1.8
    from: poggit_pmmp
  - version: 0.1.7
    from: poggit_pmmp
  - version: 0.1.6
    from: poggit_pmmp
  - version: 0.1.4
    from: poggit_pmmp
  - version: 0.1.3
    from: poggit_pmmp
  - version: 0.1.2
    from: poggit_pmmp
  - version: 0.1.1
    from: poggit_pmmp
  - version: 0.1.0
    from: poggit_pmmp
  - version: 0.0.9
    from: poggit_pmmp
  - version: 0.0.8
    from: poggit_pmmp
  - version: 0.0.7
    from: poggit_pmmp
  - version: 0.0.6
    from: poggit_pmmp
  - version: 0.0.5
    from: poggit_pmmp
  - version: 0.0.4
    from: poggit_pmmp
  - version: 0.0.2
    from: poggit_pmmp
  - version: 0.0.1
    from: poggit_pmmp
