revision: v1
type: plugin
name: WorldProtect
versions:
  - version: 2.3.11
    from: poggit_pmmp
  - version: 2.3.10
    from: poggit_pmmp
  - version: 2.3.9
    from: poggit_pmmp
  - version: 2.3.8
    from: poggit_pmmp
  - version: 2.3.7
    from: poggit_pmmp
  - version: 2.3.6
    from: poggit_pmmp
  - version: 2.3.5-10
    from: poggit_pmmp
  - version: 2.3.5-9
    from: poggit_pmmp
  - version: 2.3.5-7
    from: poggit_pmmp
  - version: 2.3.5-6
    from: poggit_pmmp
  - version: 2.3.5-5
    from: poggit_pmmp
  - version: 2.3.5-4
    from: poggit_pmmp
  - version: 2.3.5-2.alpha8
    from: poggit_pmmp
  - version: 2.3.5-1.alpha8
    from: poggit_pmmp
  - version: 2.3.5-dev1
    from: poggit_pmmp
  - version: 2.3.5
    from: poggit_pmmp
  - version: 2.3.2
    from: poggit_pmmp
