revision: v1
type: plugin
name: essentialsTP
versions:
  - version: 1.2.2
    from: poggit_pmmp
  - version: 1.2.1
    from: poggit_pmmp
  - version: 1.2.0-8
    from: poggit_pmmp
  - version: 1.2.0-6
    from: poggit_pmmp
  - version: 1.2.0-5
    from: poggit_pmmp
  - version: 1.2.0-2
    from: poggit_pmmp
  - version: 1.2.0-1.alpha8
    from: poggit_pmmp
  - version: 1.2.0-dev1
    from: poggit_pmmp
  - version: 1.1.1-dev2
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
