revision: v1
type: plugin
name: KnockbackFFA
versions:
  - version: 1.5.2-beta
    from: poggit_pmmp
  - version: 1.5.1-beta
    from: poggit_pmmp
  - version: 1.5-beta
    from: poggit_pmmp
  - version: 1.4-beta
    from: poggit_pmmp
  - version: 1.3-beta
    from: poggit_pmmp
  - version: 1.2.1-beta
    from: poggit_pmmp
  - version: 1.2-beta
    from: poggit_pmmp
