revision: v1
type: plugin
name: EasyCommandAutofill
versions:
  - version: '2.0'
    from: poggit_pmmp
  - version: 1.0.9
    from: poggit_pmmp
  - version: 1.0.8
    from: poggit_pmmp
  - version: 1.0.7
    from: poggit_pmmp
  - version: 1.0.6
    from: poggit_pmmp
  - version: 1.0.5
    from: poggit_pmmp
  - version: 1.0.4
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
  - version: 1.0.0-beta5
    from: poggit_pmmp
  - version: 1.0.0-beta4
    from: poggit_pmmp
  - version: 1.0.0-beta3
    from: poggit_pmmp
  - version: 1.0.0-beta2
    from: poggit_pmmp
  - version: 1.0.0-beta1
    from: poggit_pmmp
  - version: 0.1.0
    from: poggit_pmmp
