revision: v1
type: plugin
name: RestrictedSkins
versions:
  - version: 1.5.0
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
