revision: v1
type: plugin
name: Slapper
versions:
  - version: 1.6.3
    from: poggit_pmmp
  - version: 1.6.2
    from: poggit_pmmp
  - version: 1.6.1
    from: poggit_pmmp
  - version: 1.6.0
    from: poggit_pmmp
  - version: 1.5.30
    from: poggit_pmmp
  - version: 1.5.20-uhappynow
    from: poggit_pmmp
  - version: 1.5.2
    from: poggit_pmmp
  - version: 1.5.0
    from: poggit_pmmp
  - version: 1.4.3
    from: poggit_pmmp
  - version: 1.4.2
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.3.9
    from: poggit_pmmp
  - version: 1.3.8
    from: poggit_pmmp
  - version: 1.3.6
    from: poggit_pmmp
  - version: 1.3.5
    from: poggit_pmmp
  - version: 1.3.4
    from: poggit_pmmp
