revision: v1
type: plugin
name: StairSeat
versions:
  - version: 1.5.10
    from: poggit_pmmp
  - version: 1.5.9
    from: poggit_pmmp
  - version: 1.5.8
    from: poggit_pmmp
  - version: 1.5.7
    from: poggit_pmmp
  - version: 1.5.6
    from: poggit_pmmp
  - version: 1.5.5
    from: poggit_pmmp
  - version: 1.5.4
    from: poggit_pmmp
  - version: 1.5.3
    from: poggit_pmmp
  - version: 1.5.2
    from: poggit_pmmp
  - version: 1.4.2
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.3.0
    from: poggit_pmmp
  - version: 1.2.3
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
