revision: v1
type: plugin
name: BasicHUD
versions:
  - version: 1.0.8
    from: poggit_pmmp
  - version: 1.0.7
    from: poggit_pmmp
  - version: 1.0.6-5
    from: poggit_pmmp
  - version: 1.0.6-4
    from: poggit_pmmp
  - version: 1.0.6-3
    from: poggit_pmmp
