revision: v1
type: plugin
name: Parkour
versions:
  - version: 1.5.7
    from: poggit_pmmp
  - version: 1.5.6-6
    from: poggit_pmmp
  - version: 1.5.6-5
    from: poggit_pmmp
  - version: 1.5.6-4
    from: poggit_pmmp
  - version: 1.5.6-3
    from: poggit_pmmp
  - version: 1.5.3
    from: poggit_pmmp
  - version: 1.5.2
    from: poggit_pmmp
