revision: v1
type: plugin
name: GappleCooldown
versions:
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
