revision: v1
type: plugin
name: SkyBlock
versions:
  - version: 3.0.0
    from: poggit_pmmp
  - version: 2.3.3
    from: poggit_pmmp
  - version: 2.3.2
    from: poggit_pmmp
  - version: 2.2.8
    from: poggit_pmmp
  - version: 2.2.7
    from: poggit_pmmp
  - version: 2.2.6
    from: poggit_pmmp
  - version: 2.2.5
    from: poggit_pmmp
  - version: 2.2.4
    from: poggit_pmmp
  - version: 2.2.3
    from: poggit_pmmp
  - version: 2.2.2
    from: poggit_pmmp
  - version: 2.2.1
    from: poggit_pmmp
  - version: 2.2.0
    from: poggit_pmmp
  - version: 2.1.3
    from: poggit_pmmp
  - version: 2.1.2
    from: poggit_pmmp
  - version: 2.1.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
