revision: v1
type: plugin
name: PlayerVaults
versions:
  - version: 3.3.1
    from: poggit_pmmp
  - version: 3.3.0
    from: poggit_pmmp
  - version: 3.2.3
    from: poggit_pmmp
  - version: 3.2.2
    from: poggit_pmmp
  - version: 3.2.0
    from: poggit_pmmp
  - version: 3.1.1
    from: poggit_pmmp
  - version: 3.1.0
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
  - version: '3.0'
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: '2.0'
    from: poggit_pmmp
  - version: v1.0
    from: poggit_pmmp
