revision: v1
type: plugin
name: SlapperPlayerCount
versions:
  - version: 2.1.3
    from: poggit_pmmp
  - version: 2.1.2
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
