revision: v1
type: plugin
name: TopVoter
versions:
  - version: 3.2.0
    from: poggit_pmmp
  - version: 3.1.0
    from: poggit_pmmp
  - version: 3.0.0-1
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
  - version: 2.4.0
    from: poggit_pmmp
  - version: 2.3.2
    from: poggit_pmmp
  - version: 2.3.1
    from: poggit_pmmp
  - version: 2.2.1
    from: poggit_pmmp
