revision: v1
type: plugin
name: SignServerStats
versions:
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0-0.alpha11
    from: poggit_pmmp
  - version: 1.1.0-0.alpha10
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.0-0.alpha9
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
