revision: v1
type: plugin
name: GrabBag
versions:
  - version: 2.4.3
    from: poggit_pmmp
  - version: 2.4.2
    from: poggit_pmmp
  - version: 2.4.0-7
    from: poggit_pmmp
  - version: 2.4.0-6
    from: poggit_pmmp
  - version: 2.4.0-4
    from: poggit_pmmp
  - version: 2.4.0-1-dev
    from: poggit_pmmp
