revision: v1
type: plugin
name: Mission
versions:
  - version: 1.8.1
    from: poggit_pmmp
  - version: 1.8.0
    from: poggit_pmmp
  - version: 1.7.2
    from: poggit_pmmp
  - version: 1.7.1
    from: poggit_pmmp
  - version: 1.6.3
    from: poggit_pmmp
  - version: 1.6.2
    from: poggit_pmmp
  - version: 1.6.1
    from: poggit_pmmp
  - version: 1.6.0
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.2.1
    from: poggit_pmmp
