revision: v1
type: plugin
name: VoteReward
versions:
  - version: 3.0.2-5
    from: poggit_pmmp
  - version: 3.0.2-4
    from: poggit_pmmp
  - version: 3.0.2-2
    from: poggit_pmmp
  - version: 3.0.2-1.alpha8
    from: poggit_pmmp
  - version: 3.0.2-dev1
    from: poggit_pmmp
  - version: 3.0.2
    from: poggit_pmmp
