revision: v1
type: plugin
name: Clothes
versions:
  - version: '5.0'
    from: poggit_pmmp
  - version: 4.1.1
    from: poggit_pmmp
  - version: 4.1.0
    from: poggit_pmmp
  - version: 3.1.0
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
