revision: v1
type: plugin
name: RolePlay
versions:
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0-5
    from: poggit_pmmp
  - version: 1.1.0-4
    from: poggit_pmmp
  - version: 1.1.0-3
    from: poggit_pmmp
  - version: 1.1.0-2
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.9
    from: poggit_pmmp
