revision: v1
type: plugin
name: CustomShopUI
versions:
  - version: 4.0.5
    from: poggit_pmmp
  - version: 4.0.4
    from: poggit_pmmp
  - version: 4.0.3
    from: poggit_pmmp
  - version: 4.0.2
    from: poggit_pmmp
  - version: 4.0.1
    from: poggit_pmmp
  - version: 3.5.7
    from: poggit_pmmp
  - version: 3.5.6
    from: poggit_pmmp
  - version: 3.5.5
    from: poggit_pmmp
  - version: 3.5.4
    from: poggit_pmmp
  - version: 3.5.3
    from: poggit_pmmp
  - version: 3.5.0
    from: poggit_pmmp
  - version: 3.2.2
    from: poggit_pmmp
  - version: 3.2.1
    from: poggit_pmmp
  - version: 3.2.0
    from: poggit_pmmp
  - version: 3.0.3
    from: poggit_pmmp
  - version: 3.0.1
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
