revision: v1
type: plugin
name: MyPlot
versions:
  - version: 1.11.1
    from: poggit_pmmp
  - version: 1.10.1
    from: poggit_pmmp
  - version: 1.10.0
    from: poggit_pmmp
  - version: 1.9.0-pre
    from: poggit_pmmp
  - version: 1.7.1
    from: poggit_pmmp
  - version: 1.7.0
    from: poggit_pmmp
  - version: 1.6.14
    from: poggit_pmmp
  - version: 1.6.13
    from: poggit_pmmp
  - version: 1.6.12
    from: poggit_pmmp
  - version: 1.6.11
    from: poggit_pmmp
  - version: 1.6.10
    from: poggit_pmmp
  - version: 1.6.9
    from: poggit_pmmp
  - version: 1.6.8
    from: poggit_pmmp
  - version: 1.6.7
    from: poggit_pmmp
  - version: 1.6.6
    from: poggit_pmmp
  - version: 1.6.5
    from: poggit_pmmp
  - version: 1.6.4
    from: poggit_pmmp
  - version: 1.6.3
    from: poggit_pmmp
  - version: 1.6.2
    from: poggit_pmmp
  - version: 1.6.1
    from: poggit_pmmp
  - version: 1.6.0
    from: poggit_pmmp
  - version: 1.5.5
    from: poggit_pmmp
  - version: 1.5.4
    from: poggit_pmmp
  - version: 1.5.3-pre
    from: poggit_pmmp
  - version: 1.5.2
    from: poggit_pmmp
  - version: 1.5.1
    from: poggit_pmmp
  - version: 1.5.0-pre
    from: poggit_pmmp
  - version: 1.4.2
    from: poggit_pmmp
  - version: 1.4.0-1
    from: poggit_pmmp
  - version: 1.4.0
    from: poggit_pmmp
  - version: 1.3.8
    from: poggit_pmmp
  - version: 1.3.7
    from: poggit_pmmp
  - version: 1.3.6
    from: poggit_pmmp
  - version: 1.2.6
    from: poggit_pmmp
  - version: 1.2.5
    from: poggit_pmmp
  - version: 1.2.4
    from: poggit_pmmp
  - version: 1.2.3
    from: poggit_pmmp
  - version: 1.1.7-pre
    from: poggit_pmmp
