revision: v1
type: plugin
name: PCFly
versions:
  - version: 4.0.0
    from: poggit_pmmp
  - version: 3.0.0
    from: poggit_pmmp
  - version: 2.1.1
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
