revision: v1
type: plugin
name: CustomAlerts
versions:
  - version: '2.1'
    from: poggit_pmmp
  - version: '2.0'
    from: poggit_pmmp
  - version: '1.9'
    from: poggit_pmmp
  - version: 1.7.2-4
    from: poggit_pmmp
  - version: '1.8'
    from: poggit_pmmp
  - version: 1.7.2-3
    from: poggit_pmmp
  - version: 1.7.2
    from: poggit_pmmp
