revision: v1
type: plugin
name: PurePerms
versions:
  - version: 1.4.5
    from: poggit_pmmp
  - version: 1.4.4
    from: poggit_pmmp
  - version: 1.4.3
    from: poggit_pmmp
  - version: 1.4.2-c2a
    from: poggit_pmmp
  - version: 1.4.1-6
    from: poggit_pmmp
  - version: 1.4.1-5
    from: poggit_pmmp
  - version: 1.4.1-4
    from: poggit_pmmp
  - version: 1.4.1-3
    from: poggit_pmmp
  - version: 1.4.1-2
    from: poggit_pmmp
  - version: 1.4.1-1.alpha8
    from: poggit_pmmp
  - version: 1.4.1-dev2
    from: poggit_pmmp
  - version: 1.4.1-dev1
    from: poggit_pmmp
  - version: 1.4.0-INDEV
    from: poggit_pmmp
  - version: '1.4'
    from: poggit_pmmp
