revision: v1
type: plugin
name: Netherite
versions:
  - version: '2.0'
    from: poggit_pmmp
  - version: 1.2.1
    from: poggit_pmmp
  - version: '1.2'
    from: poggit_pmmp
  - version: '1.1'
    from: poggit_pmmp
  - version: '1.0'
    from: poggit_pmmp
