revision: v1
type: plugin
name: SocialSpy
versions:
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
