revision: v1
type: plugin
name: Mockingbird
versions:
  - version: '2.5'
    from: poggit_pmmp
  - version: 2.4.0
    from: poggit_pmmp
  - version: 2.3.0
    from: poggit_pmmp
  - version: 2.2.0
    from: poggit_pmmp
  - version: 2.1.0
    from: poggit_pmmp
  - version: 1.3-beta
    from: poggit_pmmp
  - version: 1.1-beta
    from: poggit_pmmp
  - version: 1.0-beta
    from: poggit_pmmp
