revision: v1
type: plugin
name: ItemCloud
versions:
  - version: 1.3.1
    from: poggit_pmmp
  - version: 1.3.0-4
    from: poggit_pmmp
  - version: 1.3.0-3
    from: poggit_pmmp
  - version: 1.3.0-2
    from: poggit_pmmp
  - version: 1.3.0-1
    from: poggit_pmmp
