revision: v1
type: plugin
name: EasyKits
versions:
  - version: 1.1.6
    from: poggit_pmmp
  - version: 1.1.5
    from: poggit_pmmp
  - version: 1.1.4
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
  - version: 1.1.2
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
  - version: 1.0.0-beta4
    from: poggit_pmmp
